language: java

git:
  depth: false

jobs:
  include:
    - stage: test
      script: sh test.sh
    - stage: deploy
      language: python
      python: "3.6"
      script: skip
      if: env(deploy) IS present
      deploy:
        - provider: script
          script: sh deploy.sh
        - provider: releases
          api_key: $GH_ACCESS_TOKEN
          tag_name: $deploy


  
